name: cntk-py35
channels:
- defaults
# For imageio:
- conda-forge
dependencies:
- h5py
- jupyter
- matplotlib
- numpy
- opencv
- pandas
- pandas-datareader==0.5.0
- pandoc
- pip
- python==3.5.5
- pyyaml
- scipy
- seaborn
- setuptools
- six
- wheel
- cython
- pip:
  - easydict
  - gym
  - keras
  - pydot-ng
  - pygame
  - pytest==3.6.2
  - sphinx-rtd-theme
  - sphinx
  - nbsphinx
  - twine
  - protobuf
  - pillow
  - imageio
  - scikit-image
  - scikit-learn