name: cntk-py27
channels:
- defaults
# For imageio:
- conda-forge
dependencies:
- h5py
- jupyter
- matplotlib
- mock
- numpy
- pandas
# Downgrade to 0.5.0 due to https://github.com/pydata/pandas-datareader/issues/495
- pandas-datareader==0.5.0
- pandoc
- pip
- python==2.7.15
- pyyaml
- scipy
- seaborn
- setuptools
- six
- wheel
- cython
- pip:
  - easydict
  - gym[atari]
  - keras
  - pydot-ng
  - pygame
  - pytest==3.6.2
  - sphinx-rtd-theme
  - sphinx
  - nbsphinx
  - twine
  - protobuf
  - pillow
  - imageio
  - scikit-image
  - scikit-learn