name: cntk-py27
channels:
- defaults
# For imageio:
- conda-forge
dependencies:
- h5py
- jupyter
- matplotlib
- numpy
- opencv
- pandas
- pandas-datareader
- pandoc
- pip
- python==2.7.15
- pyyaml
- scipy
- seaborn
- setuptools
- six
- wheel
- cython
- pip:
  - easydict
  - gym[atari]
  - keras
  - pydot-ng
  - pygame
  - pytest==3.6.2
  - sphinx-rtd-theme
  - sphinx
  - nbsphinx
  - twine
  - protobuf
  - pillow
  - imageio
  - scikit-image
  - scikit-learn